/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ASpace: typeof import('ant-design-vue/es')['Space']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    Bilibili: typeof import('./../src/components/Bilibili.vue')['default']
    Home: typeof import('./../src/components/home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    S3Upload: typeof import('./../src/components/S3Upload.vue')['default']
    Test: typeof import('./../src/components/test.vue')['default']
  }
}
